# 存储服务-主服务器
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-fs-master-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 存储服务-存储服务器
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-fs-volume-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 存储服务-文件管理服务器
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-fs-file-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
 # 存储服务-文件访问服务器
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-fs-s3-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 公共服务-缓存
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-common-cache-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 公共服务-数据库pg
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-common-db-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
# 公共服务-TURN
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-common-turn-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 监控服务-GUI服务
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-monitor-gui-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
 # 监控服务-时序数据库服务
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-monitor-db-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
  # 监控服务-节点池服务
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-monitor-pool-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
  # 三维数据库后端服务，将运行所需的文件放至io-server/build目录
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-server-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 三维数据库文档服务，将编译的文件放至io-server-doc/dist目录
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-server-doc-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 三维数据库GUI服务，将编译的文件放至io-server-gui/dist目录
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io-server-gui-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 三维模型库后端服务-数据库pg
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gw-mxk-db-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
 # 三维模型库后端服务，将运行所需的文件放至gw-mxk-server/build目录
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gw-mxk-server-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 三维模型库GUI服务，将编译的文件放至gw-mxk-gui/dist目录
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gw-mxk-gui-pvc
  namespace: iotree3d
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# Service-访问服务
apiVersion: v1
kind: Service
metadata:
  name: iotree3d-service
  namespace: iotree3d
spec:
  selector:
    app: iotree3d
  ports:
    - name: io-fs-master-9333 # 存储服务-主服务器
      protocol: TCP
      port: 9333
      targetPort: 9333
    - name: io-fs-master-19333
      protocol: TCP
      port: 19333
      targetPort: 19333
    - name: io-fs-volume-9301 # 存储服务-存储服务器
      protocol: TCP
      port: 9301
      targetPort: 9301
    - name: io-fs-file-8888 # 存储服务-文件管理服务器
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: io-fs-file-18888
      protocol: TCP
      port: 18888
      targetPort: 18888
    - name: io-fs-s3-8333 # 存储服务-文件访问服务器
      protocol: TCP
      port: 8333
      targetPort: 8333
    - name: io-common-cache-6379 # 公共服务-缓存
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: io-common-db-5432 # 公共服务-数据库pg
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: io-common-turn-3478 # 公共服务-TURN
      protocol: TCP
    - name: io-comm-gui # 监控服务-GUI服务
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: io-monitor-db # 监控服务-时序数据库服务
      protocol: TCP
      port: 9090
      targetPort: 3100
    - name: io-monitor-pool # 监控服务-节点池服务
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: io-server # 三维模型库后端服务
      protocol: TCP
      port: 8100
      targetPort: 8100
    - name: io-server-doc # 三维数据库文档服务，将编译的文件放至io-server-doc/dist目录
      protocol: TCP
      port: 80
      targetPort: 8188
    # 三维数据库GUI服务，将编译的文件放至io-server-gui/dist目录
    - name: io-server-gui
      protocol: TCP
      port: 80
      targetPort: 8000
    # 三维模型库后端服务-数据库pg
    - name: gw-mxk-db
      protocol: TCP
      port: 5432
      targetPort: 5433
    # 三维模型库后端服务，将运行所需的文件放至gw-mxk-server/build目录
    - name: gw-mxk-server
      protocol: TCP
      port: 8200
      targetPort: 8200
    # 三维模型库GUI服务，将编译的文件放至gw-mxk-gui/dist目录
    - name: gw-mxk-gui
      protocol: TCP
      port: 80
      targetPort: 8080
    
  type: NodePort

---

# 公共服务-部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotree3d-deployment
  namespace: iotree3d
  labels:
    app: iotree3d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotree3d
  template:
    metadata:
      labels:
        app: iotree3d
    spec:
      containers:
        - name: io-fs-master # 存储服务-主服务器
          image: iotree3d:latest
          ports:
            - containerPort: 9333
            - containerPort: 19333
          volumeMounts:
            - name: io-fs-master-pvc
              mountPath: /data
        - name: io-fs-volume # 存储服务-存储服务器
          image: iotree3d:latest
          ports:
            - containerPort: 9301
            - containerPort: 18080
          volumeMounts:
            - name: io-fs-master-pvc
              mountPath: /data
        - name: io-fs-file # 存储服务-文件管理服务器
          image: iotree3d:latest
          ports:
            - containerPort: 8888
            - containerPort: 18888
          volumeMounts:
            - name: io-fs-master-pvc
              mountPath: /data
        - name: io-fs-s3 # 存储服务-文件访问服务器
          image: iotree3d:latest
          ports:
            - containerPort: 8333
          volumeMounts:
            - name: io-fs-master-pvc
              mountPath: /data
        - name: io-common-cache # 公共服务-缓存
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: io-common-cache-pvc
              mountPath: /data
        - name: io-common-db # 公共服务-数据库pg
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: iotree3d
            - name: POSTGRES_PASSWORD
              value: iotree3d
            - name: POSTGRES_DB
              value: iotree3d
          volumeMounts:
            - name: io-common-db-pvc
              mountPath: /var/lib/postgresql/data
        - name: io-common-turn  # 公共服务-TURN
          image: iotree3d:latest
          volumeMounts:
            - name: io-common-cache-pvc
              mountPath: /data
        - name: io-common-gui  # 监控服务-GUI服务
          image: grafana/grafana
          ports:
            - containerPort: 3200
          volumeMounts:
            - name: io-monitor-gui-pvc
              mountPath: /var/lib/grafana
        - name: io-common-prometheus  # 监控服务-时序数据库服务
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: io-common-db-pvc
              mountPath: /prometheus/data
        - name: io-monitor-pool # 监控服务-监控池
          image: iotree3d:latest
          ports:
            - containerPort: 8500
          env:
            - name: CONSUL_LOCAL_CONFIG
              value: '{"http_config": {"response_headers" : { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "GET, OPTIONS, POST, PUT"}}}'
          volumeMounts:
            - name: io-monitor-pool-pvc
              mountPath: /consul/data
        - name: io-server # 三维数据库后端服务
          image: iotree3d:latest
          ports:
            - containerPort: 8100
          volumeMounts:
            - name: io-server-pvc
              mountPath: /app
         # 三维数据库文档服务，将编译的文件放至io-server-doc/dist目录
        - name: io-docs # 三维数据库文档服务
          image: iotree3d:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: io-docs-pvc
              mountPath: /app  
        # 三维数据库GUI服务，将编译的文件放至io-server-gui/dist目录
        - name: io-server-gui # 三维数据库GUI服务
          image: iotree3d:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: io-server-gui-pvc
              mountPath: /app
        # 三维模型库后端服务-数据库pg
        - name: gw-mxk-db # 公共服务-数据库pg
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: gw-mxk-db-pvc
              mountPath: /var/lib/postgresql/data
        # 三维模型库后端服务，将运行所需的文件放至gw-mxk-server/build目录 
        - name: gw-mxk-server # 三维模型库后端服务
          image: iotree3d:latest
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: gw-mxk-server-pvc
              mountPath: /app
        # 三维模型库GUI服务，将编译的文件放至gw-mxk-gui/dist目录
        - name: gw-mxk-gui # 三维模型库GUI服务
          image: iotree3d:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: gw-mxk-gui-pvc
              mountPath: /app
      volumes:
        - name: io-fs-master-pvc # 存储服务-主服务器
          persistentVolumeClaim:
            claimName: io-fs-master-pvc
        - name: io-fs-volume-pvc # 存储服务-存储服务器
          persistentVolumeClaim:
            claimName: io-fs-volume-pvc
        - name: io-fs-file-pvc # 存储服务-文件管理服务器
          persistentVolumeClaim:
            claimName: io-fs-file-pvc
        - name: io-fs-s3-pvc # 存储服务-文件访问服务器
          persistentVolumeClaim:
            claimName: io-fs-s3-pvc
        - name: io-common-cache-pvc # 公共服务-缓存
          persistentVolumeClaim:
            claimName: io-common-cache-pvc
        - name: io-common-db-pvc # 公共服务-数据库pg
          persistentVolumeClaim:
            claimName: io-common-db-pvc
        - name: io-common-turn-pvc # 公共服务-TURN
          persistentVolumeClaim:
            claimName: io-common-turn-pvc
        - name: io-monitor-gui-pvc # 监控服务-GUI服务
          persistentVolumeClaim:
            claimName: io-monitor-gui-pvc
        - name: io-common-prometheus-pvc # 监控服务-时序数据库服务
          persistentVolumeClaim:
            claimName: io-monitor-db-pvc
        - name: io-monitor-pool-pvc # 监控服务-监控池
          persistentVolumeClaim:
            claimName: io-monitor-pool-pvc
        - name: io-server-pvc # 三维模型库后端服务
          persistentVolumeClaim:
            claimName: io-server-pvc
        - name: io-server-doc-pvc # 三维模型库后端服务-文档
          persistentVolumeClaim:
            claimName: io-server-doc-pvc
        - name: io-server-gui-pvc # 三维模型库GUI服务
          persistentVolumeClaim:
            claimName: io-server-gui-pvc
        - name: io-server-gui-pvc # 三维模型库GUI服务
          persistentVolumeClaim:
            claimName: io-server-gui-pvc
        - name: gw-mxk-db-pvc # 三维模型库后端服务-数据库pg
          persistentVolumeClaim:
            claimName: gw-mxk-db-pvc
        - name: gw-mxk-server-pvc # 三维模型库后端服务
          persistentVolumeClaim:
            claimName: gw-mxk-server-pvc
        - name: gw-mxk-gui-pvc # 三维模型库GUI服务
          persistentVolumeClaim:
            claimName: gw-mxk-gui-pvc
