[package]
name = "transactions"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
reqwest = "0.12.15"
serde_json = "1.0.140"
shellexpand = "3.1.0"
solana-client = "2.2.6"
solana-sdk = "2.2.2"
spl-memo = "6.0.0"
tokio = "1.44.1"
